### 添加地址
POST http://{{host}}/shippings
Content-Type: application/json

{
  "receiverName": "test",
  "receiverPhone": "test",
  "receiverMobile": "test",
  "receiverProvince": "test",
  "receiverCity": "test",
  "receiverDistrict": "test",
  "receiverAddress": "test",
  "receiverZip": "test"
}

### 修改地址
PUT http://{{host}}/shippings/9
Content-Type: application/json

{
  "receiverName": "good",
  "receiverPhone": "test",
  "receiverMobile": "test",
  "receiverProvince": "test",
  "receiverCity": "test",
  "receiverDistrict": "test",
  "receiverAddress": "test",
  "receiverZip": "test"
}

### 查询地址列表
GET http://{{host}}/shippings

### 删除地址
DELETE http://{{host}}/shippings/9
