### 用户登录
POST http://{{host}}/user/login
Content-Type: application/json

{
  "username": "jack",
  "password": "jack"
}

### 获取用户信息
GET http://{{host}}/user

### 用户登出
POST http://{{host}}/user/logout

### 用户注册
POST http://localhost:8080/user/register
Content-Type: application/json

{
  "username": "admin",
  "password": "admin",
  "email": "admin@163.com"
}


